### ISSUE TITLE
Unreviewed Content bypass no longer working

### ISSUE THREAD

**Issue by SebGay** [sixP-NaraKa/reddit-nsfw-unblocker#4]
Thanks for the great extension!

I am having problems that the feature interoduced in #2 no longer works. 

![Screenshot_20241223-204646_Fennec](https://github.com/user-attachments/assets/89301e21-e17d-449d-bb3a-e56beee638ed)

I am using Fennec 133.0.3 (Build #1330320) with the addon version 0.5.0 installed via Firefox addons. The regular 18+ bypass works.

Happy to provide more details as required.

**Comment by sixP-NaraKa** [comment]
Hi @SebGay,
thank you for reporting this issue. I had a look and the "Unreviewed Content" popup has also been moved around by Reddit.

I pushed the necessary change and created a new extension version 0.5.1 that resolves this issue:
https://addons.mozilla.org/de/firefox/addon/reddit-nsfw-unblocker/versions/

Happy holidays! 🎄
